image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install --user -r requirements.txt && createdb tdc_test && psql -c 'create user postgres with superuser' && export DATABASE_URL=postgres://gitpod@localhost:5432/tdc_test
